### ISSUE TITLE
16-color, 88-color, 256-color, and 24-bit color codes in cells cause an error

### ISSUE THREAD

**Issue by whitelynx** [jamestalmage/cli-table2#6]
If a cell value contains an aixterm (16-color), xterm (88-color or 256-color), or konsole (24-bit color) code, it throws `TypeError: Cannot read property 'set' of undefined`. Most modern terminals support these codes, so it would be nice to pass them through correctly.

Example:
```javascript
var ansi256Colors = require('ansi-256-colors');
var colors = require('colors');
var Table = require('cli-table2');
var util = require('util');

function testTableCell(value)
{
    try
    {
        var table = new Table({ head: [util.format('%j', value)] });
        table.push([ value ]);
        console.log(table.toString());
    }
    catch(exc)
    {
        console.error("\nError rendering value %j: %s", value, exc.stack || exc.toString());
    }
}

testTableCell(colors.green('green'));
testTableCell('\x1b[90mgray (aixterm 16-color)\x1b[m');
testTableCell(colors.gray('gray (aixterm 16-color, using "colors")'));
testTableCell('\x1b[38;5;8mgray (xterm-256color)\x1b[m');
testTableCell(ansi256Colors.fg.bright[0] + 'gray (xterm-256color, using "ansi-256-colors")' + ansi256Colors.reset);
testTableCell('\x1b[38;2;255;136;0ma bright orange (konsole 24-bit)\x1b[m');
```

Output:
```console
$ node test-cli-table2.js 
┌─────────────────────────────┐
│ "\u001b[32mgreen\u001b[39m" │
├─────────────────────────────┤
│ green                       │
└─────────────────────────────┘

Error rendering value "\u001b[90mgray (aixterm 16-color)\u001b[m": TypeError: Cannot read property 'set' of undefined
    at updateState (/home/dbronke/test/node_modules/cli-table2/src/utils.js:67:13)
    at readState (/home/dbronke/test/node_modules/cli-table2/src/utils.js:75:5)
    at Object.colorizeLines (/home/dbronke/test/node_modules/cli-table2/src/utils.js:255:13)
    at Cell.mergeTableOptions (/home/dbronke/test/node_modules/cli-table2/src/cell.js:51:24)
    at Table.<anonymous> (/home/dbronke/test/node_modules/cli-table2/src/table.js:29:12)
    at /home/dbronke/test/node_modules/cli-table2/node_modules/lodash/dist/lodash.js:901:23
    at Function.forEach (/home/dbronke/test/node_modules/cli-table2/node_modules/lodash/dist/lodash.js:3297:15)
    at Table.<anonymous> (/home/dbronke/test/node_modules/cli-table2/src/table.js:28:7)
    at /home/dbronke/test/node_modules/cli-table2/node_modules/lodash/dist/lodash.js:901:23
    at Function.forEach (/home/dbronke/test/node_modules/cli-table2/node_modules/lodash/dist/lodash.js:3297:15)

Error rendering value "\u001b[90mgray (aixterm 16-color, using \"colors\")\u001b[39m": TypeError: Cannot read property 'set' of undefined
    at updateState (/home/dbronke/test/node_modules/cli-table2/src/utils.js:67:13)
    at readState (/home/dbronke/test/node_modules/cli-table2/src/utils.js:75:5)
    at Object.colorizeLines (/home/dbronke/test/node_modules/cli-table2/src/utils.js:255:13)
    at Cell.mergeTableOptions (/home/dbronke/test/node_modules/cli-table2/src/cell.js:51:24)
    at Table.<anonymous> (/home/dbronke/test/node_modules/cli-table2/src/table.js:29:12)
    at /home/dbronke/test/node_modules/cli-table2/node_modules/lodash/dist/lodash.js:901:23
    at Function.forEach (/home/dbronke/test/node_modules/cli-table2/node_modules/lodash/dist/lodash.js:3297:15)
    at Table.<anonymous> (/home/dbronke/test/node_modules/cli-table2/src/table.js:28:7)
    at /home/dbronke/test/node_modules/cli-table2/node_modules/lodash/dist/lodash.js:901:23
    at Function.forEach (/home/dbronke/test/node_modules/cli-table2/node_modules/lodash/dist/lodash.js:3297:15)

Error rendering value "\u001b[38;5;8mgray (xterm-256color)\u001b[m": TypeError: Cannot read property 'set' of undefined
    at updateState (/home/dbronke/test/node_modules/cli-table2/src/utils.js:67:13)
    at readState (/home/dbronke/test/node_modules/cli-table2/src/utils.js:75:5)
    at Object.colorizeLines (/home/dbronke/test/node_modules/cli-table2/src/utils.js:255:13)
    at Cell.mergeTableOptions (/home/dbronke/test/node_modules/cli-table2/src/cell.js:51:24)
    at Table.<anonymous> (/home/dbronke/test/node_modules/cli-table2/src/table.js:29:12)
    at /home/dbronke/test/node_modules/cli-table2/node_modules/lodash/dist/lodash.js:901:23
    at Function.forEach (/home/dbronke/test/node_modules/cli-table2/node_modules/lodash/dist/lodash.js:3297:15)
    at Table.<anonymous> (/home/dbronke/test/node_modules/cli-table2/src/table.js:28:7)
    at /home/dbronke/test/node_modules/cli-table2/node_modules/lodash/dist/lodash.js:901:23
    at Function.forEach (/home/dbronke/test/node_modules/cli-table2/node_modules/lodash/dist/lodash.js:3297:15)

Error rendering value "\u001b[38;5;8mgray (xterm-256color, using \"ansi-256-colors\")\u001b[0m": TypeError: Cannot read property 'set' of undefined
    at updateState (/home/dbronke/test/node_modules/cli-table2/src/utils.js:67:13)
    at readState (/home/dbronke/test/node_modules/cli-table2/src/utils.js:75:5)
    at Object.colorizeLines (/home/dbronke/test/node_modules/cli-table2/src/utils.js:255:13)
    at Cell.mergeTableOptions (/home/dbronke/test/node_modules/cli-table2/src/cell.js:51:24)
    at Table.<anonymous> (/home/dbronke/test/node_modules/cli-table2/src/table.js:29:12)
    at /home/dbronke/test/node_modules/cli-table2/node_modules/lodash/dist/lodash.js:901:23
    at Function.forEach (/home/dbronke/test/node_modules/cli-table2/node_modules/lodash/dist/lodash.js:3297:15)
    at Table.<anonymous> (/home/dbronke/test/node_modules/cli-table2/src/table.js:28:7)
    at /home/dbronke/test/node_modules/cli-table2/node_modules/lodash/dist/lodash.js:901:23
    at Function.forEach (/home/dbronke/test/node_modules/cli-table2/node_modules/lodash/dist/lodash.js:3297:15)

Error rendering value "\u001b[38;2;255;136;0ma bright orange (konsole 24-bit)\u001b[m": TypeError: Cannot read property 'set' of undefined
    at updateState (/home/dbronke/test/node_modules/cli-table2/src/utils.js:67:13)
    at readState (/home/dbronke/test/node_modules/cli-table2/src/utils.js:75:5)
    at Object.colorizeLines (/home/dbronke/test/node_modules/cli-table2/src/utils.js:255:13)
    at Cell.mergeTableOptions (/home/dbronke/test/node_modules/cli-table2/src/cell.js:51:24)
    at Table.<anonymous> (/home/dbronke/test/node_modules/cli-table2/src/table.js:29:12)
    at /home/dbronke/test/node_modules/cli-table2/node_modules/lodash/dist/lodash.js:901:23
    at Function.forEach (/home/dbronke/test/node_modules/cli-table2/node_modules/lodash/dist/lodash.js:3297:15)
    at Table.<anonymous> (/home/dbronke/test/node_modules/cli-table2/src/table.js:28:7)
    at /home/dbronke/test/node_modules/cli-table2/node_modules/lodash/dist/lodash.js:901:23
    at Function.forEach (/home/dbronke/test/node_modules/cli-table2/node_modules/lodash/dist/lodash.js:3297:15)
```

References:
- ["ANSI escape code" on Wikipedia](https://en.wikipedia.org/wiki/ANSI_escape_code#Colors)
- ["Functions using CSI, ordered by the final character(s)" from XTerm Control Sequences](http://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-Functions-using-CSI-_-ordered-by-the-final-character_s_)
- [README.moreColors from Konsole](https://projects.kde.org/projects/kde/applications/konsole/repository/revisions/master/entry/doc/user/README.moreColors)

**Comment by whitelynx** [comment]
Looking at the code that's doing that, it seems like using [ansi-state](https://www.npmjs.com/package/ansi-state) or something similar would be preferable to maintaining your own ANSI escape code parsing logic.

**Comment by jamestalmage** [comment]
`ansi-state` looks cool, but it doesn't have a mechanism for getting `n` characters from a string (where `n` is printable characters). This is required for correctly implementing word-wrap and truncation.

I will try to address some of those escape codes (at the very least, it shouldn't throw), just not sure `ansi-state` is going to be the right solution.

**Comment by jamestalmage** [comment]
I take it that an "empty" escape string is a reset. By empty, I mean nothing between `[` and `m` (`\u001b[m` or `\x1b[m`).
Everything I read says it should have a`0` (`\u001b[0m` or `\x1b[m`).
How sure are you that the "empty" version is actually a reset (with sources if available please)?

**Comment by jamestalmage** [comment]
From what I can tell, there are two issues here.

- I am not addressing the `reset` code (see #7).
- I am not parsing aixterm codes (see #8).

**Comment by jamestalmage** [comment]
I am closing this issue in favor of #7, #8 - but let's keep the discussion here.

**Comment by whitelynx** [comment]
I couldn't remember where I had first seen it, but that behavior is defined in the [ECMA-48 spec](http://www.ecma-international.org/publications/standards/Ecma-048.htm), section 8.3.117:
> **SGR - SELECT GRAPHIC RENDITION**
> Notation: (Ps...)
> Representation: CSI Ps... 06/13
> Parameter default value: Ps = 0

The way the ECMA-48 spec is worded is a bit awkward to read. (for instance, "06/13" means the character with `6` and `13` (resp. `6` and `D` in hexadecimal) as the two halves of its representative byte; this equates to the character `m`)

The [XTerm Control Sequences](http://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-Functions-using-CSI-_-ordered-by-the-final-character_s_) document also shows `0` as the default for SGR: 
> CSI _Pm_ m  Character Attributes (SGR).
> &nbsp;&nbsp;&nbsp;&nbsp;_Ps_ = 0  -> Normal (default).
> _[...]_

**Comment by jamestalmage** [comment]
From the [ECMA-48 spec][ecma-48].

> **5.4.2 Parameter string format**
> ...
>   e) An empty parameter sub-string represents a default value which depends on the control function.
>
>   f) In each parameter sub-string, leading bit combinations 03/00 are not significant and may be omitted. If the parameter sub-string consists of bit combinations 03/00 only, at least one of them must be retained to indicate the zero value of the sub-string. 

Note: `03/00` is the zero (`0`) character

While (e) and (f) seem to be in direct conflict, I am going to go ahead and allow for the empty string.

[ecma-48]:http://www.ecma-international.org/publications/standards/Ecma-048.htm

**Comment by jamestalmage** [comment]
Also, it says leading `0`'s "may" be omitted (not "must"), so I really should allow for leading zeros to any code.

**Comment by jamestalmage** [comment]
fix published in `0.1.6`

**Comment by whitelynx** [comment]
@jamestalmage: Thank you! I made a comment on f92d128, but it's just a minor point about the unit tests.

**Comment by jamestalmage** [comment]
Fair enough. Added to the issue tracker. I'm busy with other things ATM. If it's really bugging you, feel free to submit a PR.
